### ISSUE TITLE
This request was aborted because it appears to be forged

### ISSUE THREAD

**Issue by matjazpotocnik** [ryancramerdesign/LoginRegister#1]
Hi, Ryan !

I was playing with this module on the demo site and got this error. I admit that I abused the login form (resubmiting, going back, login/logout in multiple tabs) and I'm familiar with this error, but frontend users would be confused ... 

Error: Exception: This request was aborted because it appears to be forged. (in /home/www/demopro/regular/wire/core/SessionCSRF.php line 190)

#0 /home/www/demopro/regular/site/modules/LoginRegister/LoginRegister.module(594): ProcessWire\SessionCSRF->validate()
#1 /home/www/demopro/regular/wire/core/Wire.php(383): ProcessWire\LoginRegister->___processRegisterForm(Object(ProcessWire\InputfieldForm))
#2 /home/www/demopro/regular/wire/core/WireHooks.php(698): ProcessWire\Wire->_callMethod('___processRegis...', Array)
#3 /home/www/demopro/regular/wire/core/Wire.php(442): ProcessWire\WireHooks->runHooks(Object(ProcessWire\LoginRegister), 'processRegister...', Array)
#4 /home/www/demopro/regular/site/modules/LoginRegister/LoginRegister.module(295): ProcessWire\Wire->__call('processRegister...', Array)
#5 /home/www/demopro/regular/wire/core/Wire.php(380): ProcessWire\LoginRegister->___execute()
#6 /home/www/demopro/regular/wire/core/WireHooks.php(698): ProcessWire\Wire->_callMethod('___execute', Array)
#7 /home/www/demopro

This error message was shown because: site is in debug mode. ($config->debug = true; => /site/config.php). Error has been logged.

**Comment by ryancramerdesign** [comment]
The site is in debug mode, so it's doing what it should. If it weren't in
debug mode, it would show a 500 error. If you prefer, you can wrap the
module execute() call in a try/catch to provide your own error handler too.

**Comment by matjazpotocnik** [comment]
Try/catch is just fine. Thanks for info.

**Comment by ryancramerdesign** [comment]
No problem, thanks for the testing.

**Comment by somatonic** [comment]
This is not a solution at all. It should be handled by the module not in the code of the the template/implementation.
