### ISSUE TITLE
Forgot password module doesn't work with email address

### ISSUE THREAD

**Issue by adrianbj** [ryancramerdesign/LoginRegister#7]
The ForgotPassword module needs updating because right now if you use this module with the email login option users won't even know their username, so they can't actually use the forgot password functionality.

**Comment by salvw** [comment]
I tried it and it does work with email. So the descriptive text is incorrect and has to be adjusted.

**Comment by adrianbj** [comment]
Thanks @salvanwezel - you're right. I tested this late last night and at the time it didn't work with the email address I was using but definitely working now. But yes I agree that the wording should change to ask for email address if that option is enabled in the LoginRegister module.
